### ISSUE TITLE
[Feature Request] ChatControlRed Support

### ISSUE THREAD

**Issue by Hellcode48** [max1mde/ChatBubblesAPI#1]
Implement support for chat channels from ChatControlRed

**Comment by max1mde** [comment]
> Implement support for chat channels from ChatControlRed

Is there a public API for it?
I only found this paid plugin: https://builtbybit.com/resources/chatcontrol-red-format-filter-chat.18217/

**Comment by Hellcode48** [comment]
There is:
https://github.com/kangarko/ChatControl-Red/wiki/API

**Comment by max1mde** [comment]
Do you have any experience with plugin development? Because I could write the code for a chat bubbles extension using my api to support these chat channels and you compile the plugin because you already bought it?
Because I dont think the dev will just give it to me.

**Comment by Hellcode48** [comment]
I don't really have great experience. You can try contacting the dev @ support@mineacademy.org. He might give you a API jar or something if you were to contact them

**Comment by d0ddn** [comment]
I wrote to the developer of the Chatcontrol Red plugin and hope for his response, maybe he will look at this post
