### ISSUE TITLE
Support for PacketEvents 2.6.0

### ISSUE THREAD

**Issue by FaultyFunctions** [max1mde/ChatBubblesAPI#6]
I had to update my PacketEvents version to 2.6.0 to update the plugin Typewriter, but updating PacketEvents broke BetterChatBubbles. Is there anyway you could add support for v2.6.0 of PacketEvents?

**Comment by max1mde** [comment]
> I had to update my PacketEvents version to 2.6.0 to update the plugin Typewriter, but updating PacketEvents broke BetterChatBubbles. Is there anyway you could add support for v2.6.0 of PacketEvents?

Yeah I will update it.

**Comment by max1mde** [comment]
Please test https://www.spigotmc.org/resources/115811/update?update=569148
@FaultyFunctions
